server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://fast_food_pagamento_admin:fast_food_pagamento_root@fast-food-documentdb-0.csxw4cuf3uvj.us-east-1.docdb.amazonaws.com:27017/?retryWrites=false
      database: fast_food_pagamento
  main:
    allow-bean-definition-overriding: true

aws:
  cloud:
    stack:
      auto: false
    region:
      static: us-east-1
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/372431383879
  queue:
    notificacao-pagamento:
      name: notificacao-pagamento
    notificacao-pagamento-error:
      name: notificacao-pagamento-error


