server:
  port: 8090

spring:
  mongodb:
    embedded:
      version: 4.0.0
  main:
    allow-bean-definition-overriding: true


cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: localstack
      secret-key: localstack
    end-point:
      uri: ${URL_SQS:http://localhost:4566}

aws:
  queue:
    name: notificacao-pagamento-sync

mongodb:
  authentication-database: admin
  database: fast-food-docdb-cluster
  url: ${MONGO_URL:mongodb://127.0.0.1:27017}
  username: ${MONGO_USER:root}
  password: ${MONGO_PASSWORD:rootpassword}